export const OCCUPATIONS = [
  "Student",
  "Accountant",
  "Actor / Actress",
  "Architect",
  "Artisan / Craftsperson",
  "Banker / Finance Professional",
  "Business Owner / Entrepreneur",
  "Chef / Cook",
  "Civil Servant / Government Worker",
  "Clergy / Pastor / Minister",
  "Construction Worker",
  "Consultant",
  "Content Creator / Influencer",
  "Customer Service Representative",
  "Data Analyst / Data Scientist",
  "Doctor / Physician",
  "Driver / Transporter",
  "Economist",
  "Educator / Lecturer / Professor",
  "Engineer (Civil)",
  "Engineer (Electrical)",
  "Engineer (Mechanical)",
  "Engineer (Software / IT)",
  "Farmer / Agriculturist",
  "Fashion Designer",
  "Financial Advisor",
  "Freelancer",
  "Graphic Designer",
  "Healthcare Worker",
  "HR Professional",
  "Insurance Professional",
  "Journalist / Writer",
  "Lawyer / Legal Professional",
  "Logistics / Supply Chain",
  "Marketer / Sales Professional",
  "Media / Broadcasting",
  "Military / Security Personnel",
  "Nurse / Midwife",
  "Pharmacist",
  "Pilot / Aviation",
  "Police / Law Enforcement",
  "Project Manager",
  "Psychologist / Counselor",
  "Real Estate Agent / Developer",
  "Researcher / Scientist",
  "Retired",
  "Social Worker",
  "Surveyor",
  "Teacher",
  "Trader / Merchant",
  "Unemployed",
  "Other",
];
